
import gameStyles from "@/styles/game.module.css";

export const CenterVertically = ({ children, className="" }) => (
    <div className="tableToCenterContent">
        <div className={`cellCentered ${className}`}>{children}</div>
    </div>
);

export const Panel = ({ children, className="" }) => (
    <div className={`${gameStyles.panel} ${className} neonBorder neonBoxShadowGlow purple`}>
        <div className={`${gameStyles.innerPanel} neonScrollBar purple`}>
            {children}
        </div>
    </div>
)



export const Temp = () => (
    <div>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
        <p>Beep</p>
        <p>Boop</p>
        <p>Lemon</p>
    </div>
)